# .github/workflows/database-state.yml
#
# A sample GitHub Actions workflow that:
# 1. Spins up a PostgreSQL service
# 2. Installs the PostgreSQL client
# 3. Runs database_state.sh to list databases, schemas, and tables

name: Database State

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-database-state:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h 127.0.0.1 -p 5432 -U postgres; do
            echo "Waiting for Postgres..."
            sleep 2
          done
        shell: bash

      - name: Run database_state.sh
        run: |
          chmod +x database_state.sh
          # Export environment variables so the script knows how to connect
          export PGUSER="postgres"
          export PGPASSWORD="postgres"
          export PGHOST="127.0.0.1"
          export PGPORT="5432"
          
          ./database_state.sh
        shell: bash
