name: Remove and Recreate DB

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  remove-and-recreate:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h 127.0.0.1 -p 5432 -U postgres; do
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Make remove-recreate-db.sh executable
        run: chmod +x remove-recreate-db.sh

      - name: Remove and recreate open-members DB
        run: ./remove-recreate-db.sh

      - name: Install Node dependencies
        run: npm ci

      - name: Apply migrations
        run: npx graphile-migrate migrate

      - name: Run database-state.sh
        run: |
          chmod +x database-state.sh
          ./database-state.sh
